# yaml-language-server: $schema=https://raw.githubusercontent.com/traefik/traefik-helm-chart/refs/tags/v39.0.5/traefik/values.schema.json

ingressRoute:
  dashboard:
    enabled: false
    matchRule: Host(`traefik.whitworth.nz`)
    entryPoints:
      - web

providers:
  kubernetesGateway:
    enabled: true

gateway:
  listeners:
    web:
      namespacePolicy:
        from: All
