---
version: "3"

dotenv:
  - .env

vars:
  kube_context: kind-homeops

tasks:
  bootstrap:
    cmds:
      - |
        argocd-autopilot repo bootstrap \
          --repo $ARGOCD_BOOTSTRAP_GIT_REPO \
          --git-token $ARGOCD_BOOTSTRAP_GIT_TOKEN \
          --context {{.kube_context}}
