---
version: "3"

dotenv:
  - .env

vars:
  kube_context: kind-homeops

tasks:
  bootstrap:
    cmds:
      - kubectl apply --server-side --context {{.kube_context}} -k argocd

  uninstall:
    cmds:
      - kubectl delete --context {{.kube_context}} -k argocd

  argocd-admin-password:
    cmds:
      - |
        kubectl get secret \
          --context {{.kube_context}} \
          --namespace argocd \
          argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 --decode
