apiVersion: apps/v1
kind: Deployment
metadata:
  name: garmin-grafana
  labels:
    app.kubernetes.io/name: garmin-grafana
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: garmin-grafana
  template:
    metadata:
      labels:
        app.kubernetes.io/name: garmin-grafana
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: garmin-fetch
          image: thisisarpanghosh/garmin-fetch-data:latest
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          envFrom:
            - secretRef:
                name: influxdb-auth
          env:
            - name: INFLUXDB_HOST
              value: "influxdb-influxdb2.influxdb.svc.cluster.local"
            - name: INFLUXDB_PORT
              value: "8086"
            - name: INFLUXDB_DATABASE
              value: "garmin"
            - name: INFLUXDB_ENDPOINT_IS_HTTP
              value: "True"
            - name: INFLUXDB_VERSION
              value: "1"
            - name: ALWAYS_PROCESS_FIT_FILES
              value: "True"
            - name: FETCH_INTERVAL
              value: "15min"
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - name: garmin-tokens
              mountPath: /home/appuser/.garminconnect
      volumes:
        - name: garmin-tokens
          emptyDir: {}
