apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: influxdb-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
    template:
      data:
        INFLUXDB_USERNAME: admin
        INFLUXDB_PASSWORD: "{{ .influxdbAdminPassword }}"
        INFLUXDB_ADMIN_USER: admin
        INFLUXDB_ADMIN_PASSWORD: "{{ .influxdbAdminPassword }}"
        GARMINCONNECT_EMAIL: "{{ .garminconnectEmail }}"
        GARMINCONNECT_BASE64_PASSWORD: "{{ .garminconnectPassword | b64enc }}"
  data:
    - secretKey: influxdbAdminPassword
      remoteRef:
        key: InfluxDB Credentials/admin-token
    - secretKey: garminconnectEmail
      remoteRef:
        key: Garmin Credentials/email
    - secretKey: garminconnectPassword
      remoteRef:
        key: Garmin Credentials/password
