apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-tls
spec:
  secretName: traefik-tls
  dnsNames:
    - '*.lab.whitworth.nz'
    - 'temp.lab.whitworth.nz' # workaround letsencrypt rate limits
  issuerRef:
    name: acme
    kind: Issuer
