---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: traefik
spec:
  controllerName: traefik.io/gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: traefik-gateway
  annotations:
    external-dns.alpha.kubernetes.io/target: "lab.whitworth.nz"
spec:
  gatewayClassName: traefik
  listeners:
    - name: websecure
      port: 443
      protocol: HTTPS
      hostname: "*.lab.whitworth.nz"
      tls:
        certificateRefs:
          - name: traefik-tls
      allowedRoutes:
        namespaces:
          from: All
