apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: acme
spec:
  acme:
    # Use the staging server for testing to avoid hitting Let's Encrypt rate limits.
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: acme
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
