apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-oauth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
    name: operator-oauth
  data:
    - secretKey: client_id
      remoteRef:
        key: Tailscale Operator/clientId
    - secretKey: client_secret
      remoteRef:
        key: Tailscale Operator/clientSecret
