apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: influxdb-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: InfluxDB Credentials/admin-password
    - secretKey: admin-token
      remoteRef:
        key: InfluxDB Credentials/admin-token
