apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: influxdb-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: influxdb-user
      remoteRef:
        key: InfluxDB Credentials/admin-user
    - secretKey: influxdb-password
      remoteRef:
        key: InfluxDB Credentials/admin-password
