---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
spec:
  description: A project for infra things
  destinations:
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: traefik
      server: https://kubernetes.default.svc
    - namespace: metallb-system
      server: https://kubernetes.default.svc
    - namespace: cert-manager
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/clueshh/homeops-gitops.git
    - https://github.com/metallb/metallb
    - ghcr.io/prometheus-community/charts
    - ghcr.io/traefik/helm
    - quay.io/jetstack/charts
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
