---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
spec:
  description: A project for infra things
  destinations:
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: traefik
      server: https://kubernetes.default.svc
    - namespace: metallb-system
      server: https://kubernetes.default.svc
    - namespace: cert-manager
      server: https://kubernetes.default.svc
    - namespace: external-dns
      server: https://kubernetes.default.svc
    - namespace: external-secrets
      server: https://kubernetes.default.svc
    - namespace: reloader
      server: https://kubernetes.default.svc
    - namespace: longhorn-system
      server: https://kubernetes.default.svc
    - namespace: tailscale
      server: https://kubernetes.default.svc
    - namespace: authentik
      server: https://kubernetes.default.svc
    - namespace: cnpg-system
      server: https://kubernetes.default.svc
    - namespace: adguard
      server: https://kubernetes.default.svc
    - namespace: garmin-grafana
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/clueshh/homeops-gitops.git
    - https://github.com/metallb/metallb
    - https://kubernetes-sigs.github.io/external-dns
    - https://charts.external-secrets.io
    - https://stakater.github.io/stakater-charts
    - https://pkgs.tailscale.com/helmcharts
    - https://charts.goauthentik.io
    - https://cloudnative-pg.github.io/charts
    - https://charts.longhorn.io
    - https://helm.influxdata.com
    - ghcr.io/prometheus-community/charts
    - ghcr.io/traefik/helm
    - quay.io/jetstack/charts
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
