# This is the secret created during initial bootstrap of the cluster.
# It is used by the 1password ClusterSecretStore to authenticate to 1password and fetch the secrets.
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onepassword-token
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: ExternalSecrets 1Password Service Account Auth Token/credential
        metadataPolicy: None
