apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: 1password
spec:
  provider:
    onepasswordSDK:
      vault: HomeOps
      auth:
        serviceAccountSecretRef:
          name: onepassword-token
          key: token
