apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: https://argocd.lab.whitworth.nz
  dex.config: |
    connectors:
      - config:
          issuer: https://auth.lab.whitworth.nz/application/o/argo-cd/
          clientID: 84jvn8GMB34DMjR27fRQ3fSBoplKaCGYf1EYIlRs
          clientSecret: $dex.authentik.clientSecret
          insecureEnableGroups: true
          scopes:
            - openid
            - profile
            - email
        name: authentik
        type: oidc
        id: authentik
