apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tapo-exporter-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1password
  target:
    creationPolicy: Owner
    template:
      data:
        TAPO_EMAIL: "{{ .tapoEmail }}"
        TAPO_PASSWORD: "{{ .tapoPassword }}"
  data:
    - secretKey: tapoEmail
      remoteRef:
        key: Tapo Credentials/email
    - secretKey: tapoPassword
      remoteRef:
        key: Tapo Credentials/password
