apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yml
  - deployment.yml
  - external-secret.yml
  - service-monitor.yml
  - service.yml

configMapGenerator:
  - name: grafana-dashboard-tapo-p110-exporter
    files:
      - dashboard.json
    options:
      labels:
        grafana_dashboard: "1"
