apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: infra
  sources:
    - repoURL: https://kubernetes-sigs.github.io/external-dns
      chart: external-dns
      targetRevision: 1.20.0
      helm:
        version: v3
        releaseName: external-dns
        valueFiles:
          - $values/values/external-dns.yml
    - repoURL: https://github.com/clueshh/homeops-gitops.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/clueshh/homeops-gitops.git
      path: configs/external-dns
      targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      limit: 5
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
