apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: garmin-grafana
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: infra
  sources:
    - repoURL: https://github.com/clueshh/homeops-gitops.git
      path: configs/garmin-grafana
      targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      limit: 5
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
  destination:
    namespace: garmin-grafana
    server: https://kubernetes.default.svc
