apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: infra
  sources:
    - repoURL: https://helm.influxdata.com
      chart: influxdb
      targetRevision: 4.12.5
      helm:
        version: v3
        releaseName: influxdb
        valueFiles:
          - $values/values/influxdb.yml
    - repoURL: https://github.com/clueshh/homeops-gitops.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/clueshh/homeops-gitops.git
      path: configs/influxdb
      targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      limit: 5
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
