apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: infra
  sources:
    - repoURL: ghcr.io/prometheus-community/charts
      chart: kube-prometheus-stack
      targetRevision: 82.15.1
      helm:
        version: v3
        releaseName: kube-prometheus-stack
        valueFiles:
          - $values/values/kube-prometheus-stack.yml
    - repoURL: https://github.com/clueshh/homeops-gitops.git
      targetRevision: HEAD
      ref: values
  ignoreDifferences:
    # ignore the generated secret as it contains a random password
    - group: ""
      kind: Secret
      name: kube-prometheus-stack-grafana
      namespace: monitoring
      jsonPointers:
        - /data/admin-password
    # ignore the secret checksum as it changes on every sync
    - group: apps
      kind: Deployment
      name: kube-prometheus-stack-grafana
      namespace: monitoring
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1secret
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      limit: 5
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
    - ServerSideApply=true
    - RespectIgnoreDifferences=true
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
