apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: infra
  sources:
    - repoURL: ghcr.io/prometheus-community/charts/kube-prometheus-stack
      chart: kube-prometheus-stack
      targetRevision: 82.15.1
      helm:
        version: v3
        releaseName: kube-prometheus-stack
      valueFiles:
        - $values/values/kube-prometheus-stack.yml
    - repoURL: https://github.com/clueshh/homeops-gitops.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      limit: 5
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
  destination:
    namespace: kube-prometheus-stack
    server: https://kubernetes.default.svc
