apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media-storage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "25"
spec:
  project: applications
  sources:
    - repoURL: https://github.com/clueshh/homeops-gitops.git
      path: configs/media-storage
      targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      limit: 5
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
  destination:
    server: https://kubernetes.default.svc
