apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: infra
  sources:
    - repoURL: https://github.com/metallb/metallb
      path: config/native
      targetRevision: v0.15.3
    - repoURL: https://github.com/clueshh/homeops-gitops.git
      path: configs/metallb
      targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      limit: 5
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
