apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prowlarr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  project: applications
  sources:
    - repoURL: https://stakater.github.io/stakater-charts
      chart: application
      targetRevision: 6.16.1
      helm:
        version: v3
        releaseName: prowlarr
        valueFiles:
          - $values/values/prowlarr.yml
    - repoURL: https://github.com/clueshh/homeops-gitops.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      limit: 5
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
  destination:
    namespace: prowlarr
    server: https://kubernetes.default.svc
